# SmartMart Retail Analytics — NumPy Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

Two main NumPy arrays are provided:
1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.


## Part 1: Dataset Creation

In [1]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees (rows = stores, columns = categories)
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees (rows = stores, columns = categories)
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)


Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


## Part 2: Basic Array Understanding

### Question 1: Array Dimensions
Display number of dimensions, shape, size, dtype, and memory usage of `sales_data`.

In [2]:
# Number of dimensions in sales_data
print("Number of dimensions:", sales_data.ndim)

# Shape of sales_data -> (stores, categories)
print("Shape of sales_data:", sales_data.shape)

# Total number of values
print("Total number of values:", sales_data.size)

# Data type of the array
print("Data type of the array:", sales_data.dtype)

# Memory occupied by the array (in bytes)
print("Memory occupied (bytes):", sales_data.nbytes)


Number of dimensions: 2
Shape of sales_data: (5, 6)
Total number of values: 30
Data type of the array: int64
Memory occupied (bytes): 240


### Question 2: Store and Category Count

In [3]:
# Total number of stores
num_stores = stores.shape[0]

# Total number of product categories
num_categories = categories.shape[0]

# Total number of store-category combinations
num_combinations = sales_data.size

print("Total number of stores:", num_stores)
print("Total number of product categories:", num_categories)
print("Total number of store-category combinations:", num_combinations)


Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


### Question 3: Sales Data Type Conversion

In [4]:
# Convert sales_data to float32 and float64
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("float32 dtype:", sales_float32.dtype, "| memory (bytes):", sales_float32.nbytes)
print("float64 dtype:", sales_float64.dtype, "| memory (bytes):", sales_float64.nbytes)
print("Memory difference (bytes):", sales_float64.nbytes - sales_float32.nbytes)


float32 dtype: float32 | memory (bytes): 120
float64 dtype: float64 | memory (bytes): 240
Memory difference (bytes): 120


## Part 3: Indexing and Data Extraction

### Question 4: Bengaluru Store Analysis

In [5]:
# Row index for Bengaluru
bengaluru_idx = np.where(stores == "Bengaluru")[0][0]
bengaluru_sales = sales_data[bengaluru_idx, :]

print("Bengaluru sales across all categories:")
for cat, val in zip(categories, bengaluru_sales):
    print(f"{cat}: {val}")


Bengaluru sales across all categories:
Electronics: 850000
Groceries: 420000
Clothing: 310000
Furniture: 275000
Beauty: 190000
Sports: 225000


### Question 5: Mumbai Cost Analysis

In [6]:
mumbai_idx = np.where(stores == "Mumbai")[0][0]
mumbai_cost = cost_data[mumbai_idx, :]

print("Mumbai cost across all categories:")
for cat, val in zip(categories, mumbai_cost):
    print(f"{cat}: {val}")


Mumbai cost across all categories:
Electronics: 790000
Groceries: 390000
Clothing: 265000
Furniture: 250000
Beauty: 165000
Sports: 205000


### Question 6: Electronics Sales Across Stores

In [7]:
electronics_idx = np.where(categories == "Electronics")[0][0]
electronics_sales = sales_data[:, electronics_idx]

print("Electronics sales across all stores:")
for st, val in zip(stores, electronics_sales):
    print(f"{st}: {val}")


Electronics sales across all stores:
Bengaluru: 850000
Hyderabad: 780000
Chennai: 920000
Mumbai: 1050000
Pune: 690000


### Question 7: Clothing Cost Across Stores

In [8]:
clothing_idx = np.where(categories == "Clothing")[0][0]
clothing_cost = cost_data[:, clothing_idx]

print("Clothing cost across all stores:")
for st, val in zip(stores, clothing_cost):
    print(f"{st}: {val}")


Clothing cost across all stores:
Bengaluru: 220000
Hyderabad: 210000
Chennai: 245000
Mumbai: 265000
Pune: 205000


### Question 8: Hyderabad Furniture Performance

In [9]:
hyd_idx = np.where(stores == "Hyderabad")[0][0]
furniture_idx = np.where(categories == "Furniture")[0][0]

hyd_furniture_sales = sales_data[hyd_idx, furniture_idx]
hyd_furniture_cost = cost_data[hyd_idx, furniture_idx]
hyd_furniture_profit = hyd_furniture_sales - hyd_furniture_cost

print("Hyderabad Furniture Sales:", hyd_furniture_sales)
print("Hyderabad Furniture Cost:", hyd_furniture_cost)
print("Hyderabad Furniture Profit:", hyd_furniture_profit)


Hyderabad Furniture Sales: 310000
Hyderabad Furniture Cost: 225000
Hyderabad Furniture Profit: 85000


### Question 9: Chennai Category Range (Groceries to Furniture)

In [10]:
chennai_idx = np.where(stores == "Chennai")[0][0]

# Groceries=1, Clothing=2, Furniture=3 -> slice [1:4]
chennai_range = sales_data[chennai_idx, 1:4]

print("Chennai sales for Groceries, Clothing, Furniture:")
for cat, val in zip(categories[1:4], chennai_range):
    print(f"{cat}: {val}")


Chennai sales for Groceries, Clothing, Furniture:
Groceries: 390000
Clothing: 340000
Furniture: 260000


### Question 10: Selected Store Analysis (Advanced Indexing)

In [11]:
selected_stores = ["Bengaluru", "Chennai", "Pune"]
selected_categories = ["Electronics", "Clothing", "Beauty"]

store_indices = np.array([np.where(stores == s)[0][0] for s in selected_stores])
category_indices = np.array([np.where(categories == c)[0][0] for c in selected_categories])

# Advanced (fancy) indexing using np.ix_ to get the cross-section
selected_data = sales_data[np.ix_(store_indices, category_indices)]

print("Selected store-category sales matrix:")
print("Stores:", selected_stores)
print("Categories:", selected_categories)
print(selected_data)


Selected store-category sales matrix:
Stores: ['Bengaluru', 'Chennai', 'Pune']
Categories: ['Electronics', 'Clothing', 'Beauty']
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


## Part 4: Sales Aggregation

### Question 11: Company-Wide Sales

In [12]:
total_company_sales = sales_data.sum()
print("Total company-wide sales revenue:", total_company_sales)


Total company-wide sales revenue: 11675000


### Question 12: Store-Wise Sales

In [13]:
store_wise_sales = sales_data.sum(axis=1)

for st, val in zip(stores, store_wise_sales):
    print(f"{st}: {val}")


Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


### Question 13: Category-Wise Sales

In [14]:
category_wise_sales = sales_data.sum(axis=0)

for cat, val in zip(categories, category_wise_sales):
    print(f"{cat}: {val}")


Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


### Question 14: Average Sales Per Store

In [15]:
avg_sales_per_store = sales_data.mean(axis=1)

for st, val in zip(stores, avg_sales_per_store):
    print(f"{st}: {val:.2f}")


Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00


### Question 15: Average Sales Per Category

In [16]:
avg_sales_per_category = sales_data.mean(axis=0)

for cat, val in zip(categories, avg_sales_per_category):
    print(f"{cat}: {val:.2f}")


Electronics: 858000.00
Groceries: 437000.00
Clothing: 320000.00
Furniture: 283000.00
Beauty: 202000.00
Sports: 235000.00


### Question 16: Highest-Selling Store

In [17]:
highest_store_idx = np.argmax(store_wise_sales)

print("Index of highest-selling store:", highest_store_idx)
print("Name of highest-selling store:", stores[highest_store_idx])
print("Total sales:", store_wise_sales[highest_store_idx])


Index of highest-selling store: 3
Name of highest-selling store: Mumbai
Total sales: 2820000


### Question 17: Lowest-Selling Store

In [18]:
lowest_store_idx = np.argmin(store_wise_sales)

print("Index of lowest-selling store:", lowest_store_idx)
print("Name of lowest-selling store:", stores[lowest_store_idx])
print("Total sales:", store_wise_sales[lowest_store_idx])


Index of lowest-selling store: 4
Name of lowest-selling store: Pune
Total sales: 1980000


### Question 18: Highest-Selling Category

In [19]:
highest_cat_idx = np.argmax(category_wise_sales)

print("Highest-selling category:", categories[highest_cat_idx])
print("Total sales:", category_wise_sales[highest_cat_idx])


Highest-selling category: Electronics
Total sales: 4290000


### Question 19: Lowest-Selling Category

In [20]:
lowest_cat_idx = np.argmin(category_wise_sales)

print("Lowest-selling category:", categories[lowest_cat_idx])
print("Total sales:", category_wise_sales[lowest_cat_idx])


Lowest-selling category: Beauty
Total sales: 1010000


## Part 5: Cost Analysis

### Question 20: Total Company Cost

In [21]:
total_company_cost = cost_data.sum()
print("Total company cost:", total_company_cost)


Total company cost: 8600000


### Question 21: Store-Wise Cost

In [22]:
store_wise_cost = cost_data.sum(axis=1)

for st, val in zip(stores, store_wise_cost):
    print(f"{st}: {val}")


Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


### Question 22: Category-Wise Cost

In [23]:
category_wise_cost = cost_data.sum(axis=0)

for cat, val in zip(categories, category_wise_cost):
    print(f"{cat}: {val}")


Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


### Question 23: Most Expensive Store

In [24]:
most_expensive_store_idx = np.argmax(store_wise_cost)

print("Most expensive store:", stores[most_expensive_store_idx])
print("Total cost:", store_wise_cost[most_expensive_store_idx])


Most expensive store: Mumbai
Total cost: 2065000


### Question 24: Lowest-Cost Store

In [25]:
lowest_cost_store_idx = np.argmin(store_wise_cost)

print("Lowest-cost store:", stores[lowest_cost_store_idx])
print("Total cost:", store_wise_cost[lowest_cost_store_idx])


Lowest-cost store: Pune
Total cost: 1475000


### Question 25: Most Expensive Product Category

In [26]:
most_expensive_cat_idx = np.argmax(category_wise_cost)

print("Most expensive category:", categories[most_expensive_cat_idx])
print("Total cost:", category_wise_cost[most_expensive_cat_idx])


Most expensive category: Electronics
Total cost: 3250000


## Part 6: Profit Analysis Using Two Arrays

### Question 26: Profit Matrix

In [27]:
# Profit for every store-category combination
profit_data = sales_data - cost_data
print("Profit Matrix:")
print(profit_data)


Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


### Question 27: Store-Wise Profit

In [28]:
store_wise_profit = profit_data.sum(axis=1)

for st, val in zip(stores, store_wise_profit):
    print(f"{st}: {val}")


Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


### Question 28: Category-Wise Profit

In [29]:
category_wise_profit = profit_data.sum(axis=0)

for cat, val in zip(categories, category_wise_profit):
    print(f"{cat}: {val}")


Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


### Question 29: Most Profitable Store

In [30]:
most_profitable_idx = np.argmax(store_wise_profit)

print("Store:", stores[most_profitable_idx])
print("Total Sales:", store_wise_sales[most_profitable_idx])
print("Total Cost:", store_wise_cost[most_profitable_idx])
print("Total Profit:", store_wise_profit[most_profitable_idx])


Store: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


### Question 30: Least Profitable Store

In [31]:
least_profitable_idx = np.argmin(store_wise_profit)

print("Store:", stores[least_profitable_idx])
print("Total Sales:", store_wise_sales[least_profitable_idx])
print("Total Cost:", store_wise_cost[least_profitable_idx])
print("Total Profit:", store_wise_profit[least_profitable_idx])


Store: Pune
Total Sales: 1980000
Total Cost: 1475000
Total Profit: 505000


### Question 31: Most Profitable Category

In [32]:
most_profitable_cat_idx = np.argmax(category_wise_profit)

print("Category:", categories[most_profitable_cat_idx])
print("Total Profit:", category_wise_profit[most_profitable_cat_idx])


Category: Electronics
Total Profit: 1040000


### Question 32: Least Profitable Category

In [33]:
least_profitable_cat_idx = np.argmin(category_wise_profit)

print("Category:", categories[least_profitable_cat_idx])
print("Total Profit:", category_wise_profit[least_profitable_cat_idx])


Category: Sports
Total Profit: 340000


### Question 33: Maximum Individual Profit

In [34]:
max_profit_flat_idx = np.argmax(profit_data)
max_store_idx, max_cat_idx = np.unravel_index(max_profit_flat_idx, profit_data.shape)

print("Maximum Individual Profit:", profit_data[max_store_idx, max_cat_idx])
print("Store:", stores[max_store_idx])
print("Category:", categories[max_cat_idx])


Maximum Individual Profit: 260000
Store: Mumbai
Category: Electronics


### Question 34: Minimum Individual Profit

In [35]:
min_profit_flat_idx = np.argmin(profit_data)
min_store_idx, min_cat_idx = np.unravel_index(min_profit_flat_idx, profit_data.shape)

print("Minimum Individual Profit:", profit_data[min_store_idx, min_cat_idx])
print("Store:", stores[min_store_idx])
print("Category:", categories[min_cat_idx])


Minimum Individual Profit: 55000
Store: Pune
Category: Furniture


## Part 7: Profit Margin Analysis

### Question 35: Profit Margin Matrix

In [36]:
# Profit margin % for every store-category combination
profit_margin = np.round((profit_data / sales_data) * 100, 2)
print("Profit Margin Matrix (%):")
print(profit_margin)


Profit Margin Matrix (%):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


### Question 36: Store-Wise Profit Margin

In [37]:
store_profit_margin = np.round((store_wise_profit / store_wise_sales) * 100, 2)

for st, val in zip(stores, store_profit_margin):
    print(f"{st}: {val}%")


Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


### Question 37: Category-Wise Profit Margin

In [38]:
category_profit_margin = np.round((category_wise_profit / category_wise_sales) * 100, 2)

for cat, val in zip(categories, category_profit_margin):
    print(f"{cat}: {val}%")


Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


### Question 38: Best Store by Profit Margin

In [39]:
best_margin_store_idx = np.argmax(store_profit_margin)

print("Store with highest profit margin:", stores[best_margin_store_idx])
print("Profit Margin:", store_profit_margin[best_margin_store_idx], "%")


Store with highest profit margin: Mumbai
Profit Margin: 26.77 %


### Question 39: Best Category by Profit Margin

In [40]:
best_margin_cat_idx = np.argmax(category_profit_margin)

print("Category with highest profit margin:", categories[best_margin_cat_idx])
print("Profit Margin:", category_profit_margin[best_margin_cat_idx], "%")


Category with highest profit margin: Beauty
Profit Margin: 34.16 %


### Question 40: Low-Margin Transactions (Below 22%)

In [41]:
# Boolean mask for margin below 22%
low_margin_mask = profit_margin < 22

store_rows, cat_cols = np.where(low_margin_mask)

print("Low-Margin Transactions (< 22%):")
for r, c in zip(store_rows, cat_cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, "
          f"Sales: {sales_data[r,c]}, Cost: {cost_data[r,c]}, "
          f"Profit: {profit_data[r,c]}, Margin: {profit_margin[r,c]}%")


Low-Margin Transactions (< 22%):


## Part 8: Boolean Filtering

### Question 41: High Sales Values (> 5,00,000)

In [42]:
high_sales_mask = sales_data > 500000
print("High sales values (> 500000):")
print(sales_data[high_sales_mask])


High sales values (> 500000):
[ 850000  780000  920000 1050000  510000  690000]


### Question 42: Low Sales Values (< 2,00,000)

In [43]:
low_sales_mask = sales_data < 200000
print("Low sales values (< 200000):")
print(sales_data[low_sales_mask])


Low sales values (< 200000):
[190000 185000 175000]


### Question 43: High Profit Values (> 1,50,000)

In [44]:
high_profit_mask = profit_data > 150000
store_rows, cat_cols = np.where(high_profit_mask)

print("High-profit combinations (> 150000):")
for r, c in zip(store_rows, cat_cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Profit: {profit_data[r,c]}")


High-profit combinations (> 150000):
Store: Bengaluru, Category: Electronics, Profit: 210000
Store: Hyderabad, Category: Electronics, Profit: 190000
Store: Chennai, Category: Electronics, Profit: 220000
Store: Mumbai, Category: Electronics, Profit: 260000
Store: Pune, Category: Electronics, Profit: 160000


### Question 44: Moderate Sales Range (2,50,000 – 5,00,000)

In [45]:
moderate_mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
print("Moderate sales values (250000 - 500000):")
print(sales_data[moderate_mask])


Moderate sales values (250000 - 500000):
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


### Question 45: Premium Performance

In [46]:
premium_mask = np.logical_and(sales_data > 500000, profit_data > 150000)
store_rows, cat_cols = np.where(premium_mask)

print("Premium-performing combinations:")
for r, c in zip(store_rows, cat_cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, "
          f"Sales: {sales_data[r,c]}, Profit: {profit_data[r,c]}")


Premium-performing combinations:
Store: Bengaluru, Category: Electronics, Sales: 850000, Profit: 210000
Store: Hyderabad, Category: Electronics, Sales: 780000, Profit: 190000
Store: Chennai, Category: Electronics, Sales: 920000, Profit: 220000
Store: Mumbai, Category: Electronics, Sales: 1050000, Profit: 260000
Store: Pune, Category: Electronics, Sales: 690000, Profit: 160000


### Question 46: Underperforming Combinations

In [47]:
underperform_mask = np.logical_and(sales_data < 250000, profit_margin < 25)
store_rows, cat_cols = np.where(underperform_mask)

print("Underperforming combinations:")
for r, c in zip(store_rows, cat_cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, "
          f"Sales: {sales_data[r,c]}, Margin: {profit_margin[r,c]}%")


Underperforming combinations:
Store: Pune, Category: Furniture, Sales: 225000, Margin: 24.44%


### Question 47: Category Performance Classification

In [48]:
performance_labels = np.select(
    [sales_data >= 500000, (sales_data >= 250000) & (sales_data <= 499999)],
    ["High", "Medium"],
    default="Low"
)

print("Sales Performance Classification:")
print(performance_labels)


Sales Performance Classification:
[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


## Part 9: Target-Based Analysis

In [49]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
print("Sales targets by category:")
for cat, val in zip(categories, sales_targets):
    print(f"{cat}: {val}")


Sales targets by category:
Electronics: 800000
Groceries: 450000
Clothing: 320000
Furniture: 300000
Beauty: 200000
Sports: 230000


### Question 48: Target Comparison

In [50]:
# Broadcasting: sales_data (5,6) compared against sales_targets (6,)
target_diff = sales_data - sales_targets
print("Difference between actual sales and targets:")
print(target_diff)


Difference between actual sales and targets:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


### Question 49: Target Achievement Matrix

In [51]:
target_achieved = sales_data >= sales_targets
print("Target Achievement Matrix (True = achieved):")
print(target_achieved)


Target Achievement Matrix (True = achieved):
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


### Question 50: Target Achievement Count

In [52]:
targets_met_per_store = target_achieved.sum(axis=1)

for st, val in zip(stores, targets_met_per_store):
    print(f"{st}: {val} out of {len(categories)} targets achieved")


Bengaluru: 1 out of 6 targets achieved
Hyderabad: 4 out of 6 targets achieved
Chennai: 2 out of 6 targets achieved
Mumbai: 6 out of 6 targets achieved
Pune: 0 out of 6 targets achieved


### Question 51: Best Target-Performing Store

In [53]:
best_target_store_idx = np.argmax(targets_met_per_store)

print("Best target-performing store:", stores[best_target_store_idx])
print("Targets achieved:", targets_met_per_store[best_target_store_idx])


Best target-performing store: Mumbai
Targets achieved: 6


### Question 52: Target Achievement by Category

In [54]:
targets_met_per_category = target_achieved.sum(axis=0)

for cat, val in zip(categories, targets_met_per_category):
    print(f"{cat}: {val} out of {len(stores)} stores achieved target")


Electronics: 3 out of 5 stores achieved target
Groceries: 2 out of 5 stores achieved target
Clothing: 2 out of 5 stores achieved target
Furniture: 2 out of 5 stores achieved target
Beauty: 2 out of 5 stores achieved target
Sports: 2 out of 5 stores achieved target


### Question 53: Sales Target Variance

In [55]:
# Variance = Actual Sales - Target Sales (per store, per category)
sales_variance = sales_data - sales_targets
print("Sales Target Variance Matrix:")
print(sales_variance)


Sales Target Variance Matrix:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


### Question 54: Percentage Above or Below Target

In [56]:
percentage_variance = np.round(((sales_data - sales_targets) / sales_targets) * 100, 2)
print("Percentage Variance from Target (%):")
print(percentage_variance)


Percentage Variance from Target (%):
[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


### Question 55: Stores Missing Electronics Target

In [57]:
electronics_idx = np.where(categories == "Electronics")[0][0]
missed_electronics_mask = sales_data[:, electronics_idx] < sales_targets[electronics_idx]

print("Stores that missed the Electronics target:")
print(stores[missed_electronics_mask])


Stores that missed the Electronics target:
['Hyderabad' 'Pune']


### Question 56: Stores Achieving All Targets

In [58]:
all_targets_achieved = np.all(target_achieved, axis=1)

print("Stores achieving ALL category targets:")
print(stores[all_targets_achieved] if all_targets_achieved.any() else "None")


Stores achieving ALL category targets:
['Mumbai']


### Question 57: Stores Achieving At Least One Target

In [59]:
any_target_achieved = np.any(target_achieved, axis=1)

print("Stores achieving AT LEAST ONE category target:")
print(stores[any_target_achieved])


Stores achieving AT LEAST ONE category target:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


## Part 10: Discount Scenario

In [60]:
discount_rates = np.array([
    0.10,  # Electronics
    0.05,  # Groceries
    0.15,  # Clothing
    0.12,  # Furniture
    0.08,  # Beauty
    0.10   # Sports
])
print("Discount rates by category:")
for cat, val in zip(categories, discount_rates):
    print(f"{cat}: {val*100:.0f}%")


Discount rates by category:
Electronics: 10%
Groceries: 5%
Clothing: 15%
Furniture: 12%
Beauty: 8%
Sports: 10%


### Question 58: Discount Amount Matrix

In [61]:
# Broadcasting discount_rates (6,) across sales_data (5,6)
discount_amount = sales_data * discount_rates
print("Discount Amount Matrix:")
print(np.round(discount_amount, 2))


Discount Amount Matrix:


[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


### Question 59: Sales After Discount

In [62]:
sales_after_discount = sales_data - discount_amount
print("Sales After Discount:")
print(np.round(sales_after_discount, 2))


Sales After Discount:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


### Question 60: Profit After Discount

In [63]:
profit_after_discount = sales_after_discount - cost_data
print("Profit After Discount:")
print(np.round(profit_after_discount, 2))


Profit After Discount:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


### Question 61: Profit Margin After Discount

In [64]:
profit_margin_after_discount = np.round((profit_after_discount / sales_after_discount) * 100, 2)
print("Profit Margin After Discount (%):")
print(profit_margin_after_discount)


Profit Margin After Discount (%):


[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


### Question 62: Loss-Making Transactions After Discount

In [65]:
loss_mask = profit_after_discount < 0
store_rows, cat_cols = np.where(loss_mask)

if len(store_rows) == 0:
    print("No store-category combination becomes loss-making after discounts.")
else:
    print("Loss-making combinations after discount:")
    for r, c in zip(store_rows, cat_cols):
        print(f"Store: {stores[r]}, Category: {categories[c]}, Profit: {profit_after_discount[r,c]:.2f}")


No store-category combination becomes loss-making after discounts.


### Question 63: Discount Impact

In [66]:
total_discount_impact = discount_amount.sum()
print("Total revenue lost due to discounts:", round(total_discount_impact, 2))


Total revenue lost due to discounts: 1146350.0


### Question 64: Store Most Affected by Discounts

In [67]:
discount_per_store = discount_amount.sum(axis=1)
most_affected_idx = np.argmax(discount_per_store)

print("Store most affected by discounts:", stores[most_affected_idx])
print("Total discount amount:", round(discount_per_store[most_affected_idx], 2))


Store most affected by discounts: Mumbai
Total discount amount: 277150.0


## Part 11: Tax and Price Adjustment

In [68]:
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
print("Tax rates by category:")
for cat, val in zip(categories, tax_rates):
    print(f"{cat}: {val*100:.0f}%")


Tax rates by category:
Electronics: 18%
Groceries: 5%
Clothing: 12%
Furniture: 18%
Beauty: 18%
Sports: 12%


### Question 65: Tax Collection Matrix

In [69]:
tax_collected = sales_data * tax_rates
print("Tax Collection Matrix:")
print(np.round(tax_collected, 2))


Tax Collection Matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


### Question 66: Sales Including Tax

In [70]:
sales_incl_tax = sales_data + tax_collected
print("Sales Including Tax:")
print(np.round(sales_incl_tax, 2))


Sales Including Tax:
[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


### Question 67: Store-Wise Tax Collection

In [71]:
store_tax = tax_collected.sum(axis=1)

for st, val in zip(stores, store_tax):
    print(f"{st}: {round(val, 2)}")


Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0


### Question 68: Category-Wise Tax Collection

In [72]:
category_tax = tax_collected.sum(axis=0)

for cat, val in zip(categories, category_tax):
    print(f"{cat}: {round(val, 2)}")


Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0


### Question 69: Highest Tax-Contributing Store

In [73]:
highest_tax_store_idx = np.argmax(store_tax)

print("Highest tax-contributing store:", stores[highest_tax_store_idx])
print("Tax collected:", round(store_tax[highest_tax_store_idx], 2))


Highest tax-contributing store: Mumbai
Tax collected: 401400.0


## Part 12: Array Modification

### Question 70: Updated Pune Electronics Sales

In [74]:
# Copy the array so the original sales_data is NOT modified
sales_data_updated = sales_data.copy()

pune_idx = np.where(stores == "Pune")[0][0]
electronics_idx = np.where(categories == "Electronics")[0][0]

sales_data_updated[pune_idx, electronics_idx] = 740000

print("Original Pune Electronics sales:", sales_data[pune_idx, electronics_idx])
print("Updated Pune Electronics sales:", sales_data_updated[pune_idx, electronics_idx])


Original Pune Electronics sales: 690000
Updated Pune Electronics sales: 740000


### Question 71: Revised Beauty Cost (-8%)

In [75]:
cost_data_revised_beauty = cost_data.astype(float).copy()
beauty_idx = np.where(categories == "Beauty")[0][0]

cost_data_revised_beauty[:, beauty_idx] = cost_data[:, beauty_idx] * (1 - 0.08)

print("Original Beauty cost:", cost_data[:, beauty_idx])
print("Revised Beauty cost (-8%):", np.round(cost_data_revised_beauty[:, beauty_idx], 2))


Original Beauty cost: [125000 140000 120000 165000 115000]
Revised Beauty cost (-8%): [115000. 128800. 110400. 151800. 105800.]


### Question 72: Furniture Cost Increase (+12%)

In [76]:
cost_data_updated_furniture = cost_data.astype(float).copy()
furniture_idx = np.where(categories == "Furniture")[0][0]

cost_data_updated_furniture[:, furniture_idx] = cost_data[:, furniture_idx] * 1.12

print("Original Furniture cost:", cost_data[:, furniture_idx])
print("Updated Furniture cost (+12%):", np.round(cost_data_updated_furniture[:, furniture_idx], 2))


Original Furniture cost: [205000 225000 195000 250000 170000]
Updated Furniture cost (+12%): [229600. 252000. 218400. 280000. 190400.]


### Question 73: Store Closure Simulation (Remove Pune)

In [77]:
pune_idx = np.where(stores == "Pune")[0][0]

sales_without_pune = np.delete(sales_data, pune_idx, axis=0)
cost_without_pune = np.delete(cost_data, pune_idx, axis=0)
stores_without_pune = np.delete(stores, pune_idx)

print("Stores after removing Pune:", stores_without_pune)
print("Sales data shape after removal:", sales_without_pune.shape)
print(sales_without_pune)


Stores after removing Pune:

 ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
Sales data shape after removal: (4, 6)
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]


### Question 74: Adding a New Store (Delhi)

In [78]:
delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])

sales_with_delhi = np.vstack([sales_data, delhi_sales])
cost_with_delhi = np.vstack([cost_data, delhi_cost])
stores_with_delhi = np.append(stores, "Delhi")

print("Updated stores list:", stores_with_delhi)
print("Sales data shape after adding Delhi:", sales_with_delhi.shape)
print(sales_with_delhi)


Updated stores list: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
Sales data shape after adding Delhi: (6, 6)
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]


### Question 75: Adding a New Product Category (Home Appliances)

In [79]:
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])
home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])

sales_with_new_cat = np.column_stack([sales_data, home_appliance_sales])
cost_with_new_cat = np.column_stack([cost_data, home_appliance_cost])
categories_with_new = np.append(categories, "Home Appliances")

print("Updated categories:", categories_with_new)
print("Sales data shape after adding category:", sales_with_new_cat.shape)
print(sales_with_new_cat)


Updated categories: ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']
Sales data shape after adding category: (5, 7)
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]


## Part 13: Sorting and Ranking

### Question 76: Sort Stores by Sales (Ascending)

In [80]:
sort_order = np.argsort(store_wise_sales)

print("Stores sorted by total sales (ascending):")
for idx in sort_order:
    print(f"{stores[idx]}: {store_wise_sales[idx]}")


Stores sorted by total sales (ascending):
Pune: 1980000
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000


### Question 77: Rank Stores by Profit (Highest to Lowest)

In [81]:
profit_rank_order = np.argsort(store_wise_profit)[::-1]

print("Stores ranked by profit (highest to lowest):")
for rank, idx in enumerate(profit_rank_order, start=1):
    print(f"Rank {rank}: {stores[idx]} - Profit: {store_wise_profit[idx]}")


Stores ranked by profit (highest to lowest):
Rank 1: Mumbai - Profit: 755000
Rank 2: Hyderabad - Profit: 610000
Rank 3: Bengaluru - Profit: 605000
Rank 4: Chennai - Profit: 600000
Rank 5: Pune - Profit: 505000


### Question 78: Sort Categories by Revenue (Highest to Lowest)

In [82]:
cat_revenue_order = np.argsort(category_wise_sales)[::-1]

print("Categories sorted by revenue (highest to lowest):")
for idx in cat_revenue_order:
    print(f"{categories[idx]}: {category_wise_sales[idx]}")


Categories sorted by revenue (highest to lowest):
Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Sports: 1175000
Beauty: 1010000


### Question 79: Top Three Store-Category Sales

In [83]:
flat_sales = sales_data.flatten()
top3_flat_idx = np.argsort(flat_sales)[::-1][:3]
top3_positions = [np.unravel_index(i, sales_data.shape) for i in top3_flat_idx]

print("Top 3 individual sales values:")
for r, c in top3_positions:
    print(f"Store: {stores[r]}, Category: {categories[c]}, Sales: {sales_data[r,c]}")


Top 3 individual sales values:
Store: Mumbai, Category: Electronics, Sales: 1050000
Store: Chennai, Category: Electronics, Sales: 920000
Store: Bengaluru, Category: Electronics, Sales: 850000


### Question 80: Bottom Three Profits

In [84]:
flat_profit = profit_data.flatten()
bottom3_flat_idx = np.argsort(flat_profit)[:3]
bottom3_positions = [np.unravel_index(i, profit_data.shape) for i in bottom3_flat_idx]

print("Bottom 3 profit values:")
for r, c in bottom3_positions:
    print(f"Store: {stores[r]}, Category: {categories[c]}, Profit: {profit_data[r,c]}")


Bottom 3 profit values:
Store: Pune, Category: Furniture, Profit: 55000
Store: Pune, Category: Sports, Profit: 60000
Store: Chennai, Category: Sports, Profit: 60000


## Part 14: Statistical Analysis

### Question 81: Sales Statistics

In [85]:
print("Minimum:", sales_data.min())
print("Maximum:", sales_data.max())
print("Mean:", round(sales_data.mean(), 2))
print("Median:", np.median(sales_data))
print("Standard Deviation:", round(sales_data.std(), 2))
print("Variance:", round(sales_data.var(), 2))
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))


Minimum: 175000
Maximum: 1050000
Mean: 389166.67
Median: 302500.0
Standard Deviation: 230322.54
Variance: 53048472222.22


25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


### Question 82: Store-Wise Standard Deviation

In [86]:
store_std = sales_data.std(axis=1)

for st, val in zip(stores, store_std):
    print(f"{st}: {round(val, 2)}")

most_variable_store_idx = np.argmax(store_std)
print("\nStore with most variation across categories:", stores[most_variable_store_idx])


Bengaluru: 223059.53
Hyderabad: 194502.57
Chennai: 249265.59
Mumbai: 271860.87
Pune: 177200.45

Store with most variation across categories: Mumbai


### Question 83: Category-Wise Standard Deviation

In [87]:
category_std = sales_data.std(axis=0)

for cat, val in zip(categories, category_std):
    print(f"{cat}: {round(val, 2)}")

most_variable_cat_idx = np.argmax(category_std)
print("\nCategory with highest variation across stores:", categories[most_variable_cat_idx])


Electronics: 122539.79
Groceries: 43312.82
Clothing: 33911.65
Furniture: 41303.75
Beauty: 26570.66
Sports: 29832.87

Category with highest variation across stores: Electronics


### Question 84: Sales Above Company Average

In [88]:
company_avg_sales = sales_data.mean()
above_avg_count = np.sum(sales_data > company_avg_sales)

print("Company-wide average sales:", round(company_avg_sales, 2))
print("Number of values above average:", above_avg_count)


Company-wide average sales: 389166.67
Number of values above average: 10


### Question 85: Outlier Detection

In [89]:
threshold = sales_data.mean() + 1.5 * sales_data.std()
outlier_mask = sales_data > threshold

print("Outlier threshold (Mean + 1.5*Std):", round(threshold, 2))
print("Outlier sales values:", sales_data[outlier_mask])

rows, cols = np.where(outlier_mask)
for r, c in zip(rows, cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Sales: {sales_data[r,c]}")


Outlier threshold (Mean + 1.5*Std): 734650.48
Outlier sales values: [ 850000  780000  920000 1050000]
Store: Bengaluru, Category: Electronics, Sales: 850000
Store: Hyderabad, Category: Electronics, Sales: 780000
Store: Chennai, Category: Electronics, Sales: 920000
Store: Mumbai, Category: Electronics, Sales: 1050000


## Part 15: Reshaping and Transformation

### Question 86: Flatten Sales Data

In [90]:
flattened = sales_data.flatten()
raveled = sales_data.ravel()

print("Flattened array:", flattened)
print("Raveled array:", raveled)

print("""
Difference:
- flatten() ALWAYS returns a copy of the data. Modifying the flattened
  array will NOT affect the original sales_data.
- ravel() returns a view of the original array whenever possible
  (no copy is made unless required, e.g. non-contiguous memory).
  Modifying the raveled array MAY affect the original sales_data.
""")


Flattened array: [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Raveled array: [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Difference:
- flatten() ALWAYS returns a copy of the data. Modifying the flattened
  array will NOT affect the original sales_data.
- ravel() returns a view of the original array whenever possible
  (no copy is made unless required, e.g. non-contiguous memory).
  Modifying the raveled array MAY affect the original sales_data.



### Question 87: Reshape Sales Data

In [91]:
reshape_3x10 = sales_data.reshape(3, 10)
reshape_10x3 = sales_data.reshape(10, 3)
reshape_2x15 = sales_data.reshape(2, 15)
reshape_15x2 = sales_data.reshape(15, 2)

print("3x10:\n", reshape_3x10)
print("10x3:\n", reshape_10x3)
print("2x15:\n", reshape_2x15)
print("15x2:\n", reshape_15x2)

# Verify no data lost - total sum must match in every reshape
print("\nData integrity check (all True means no data lost):")
print(sales_data.sum() == reshape_3x10.sum() == reshape_10x3.sum() == reshape_2x15.sum() == reshape_15x2.sum())


3x10:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
10x3:
 [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
2x15:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
15x2:
 [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 3

### Question 88: Transpose Sales Data

In [92]:
sales_transposed = sales_data.T

print("Transposed shape (categories x stores):", sales_transposed.shape)
print(sales_transposed)


Transposed shape (categories x stores): (6, 5)
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


### Question 89: Combined Sales and Cost Array

In [93]:
combined_vertical = np.vstack([sales_data, cost_data])

print("Combined array shape:", combined_vertical.shape)
print(combined_vertical)


Combined array shape: (10, 6)
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]


### Question 90: Store-Level Combined Data (3D)

In [94]:
combined_3d = np.stack([sales_data, cost_data])

print("3D combined array shape:", combined_3d.shape)
print("Layer 0 (sales):\n", combined_3d[0])
print("Layer 1 (cost):\n", combined_3d[1])


3D combined array shape: (2, 5, 6)
Layer 0 (sales):
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Layer 1 (cost):
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


## Part 16: Missing Data Scenario

In [95]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
print(sales_with_missing)


[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]

### Question 91: Missing Value Detection

In [96]:
missing_mask = np.isnan(sales_with_missing)
total_missing = np.sum(missing_mask)
rows, cols = np.where(missing_mask)

print("Total missing values:", total_missing)
print("Locations (row, col):", list(zip(rows, cols)))

print("\nStores and categories containing missing values:")
for r, c in zip(rows, cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}")


Total missing values: 4
Locations (row, col): [(np.int64(0), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(4))]

Stores and categories containing missing values:
Store: Bengaluru, Category: Clothing
Store: Hyderabad, Category: Furniture
Store: Mumbai, Category: Groceries
Store: Pune, Category: Beauty


### Question 92: Replace Missing Values with Zero

In [97]:
sales_filled_zero = np.nan_to_num(sales_with_missing, nan=0.0)
print("Sales data with missing values replaced by zero:")
print(sales_filled_zero)


Sales data with missing values replaced by zero:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


### Question 93: Replace with Company Average

In [98]:
company_avg = np.nanmean(sales_with_missing)
sales_filled_avg = np.where(np.isnan(sales_with_missing), company_avg, sales_with_missing)

print("Company average (ignoring NaNs):", round(company_avg, 2))
print("Sales data with missing values replaced by company average:")
print(sales_filled_avg)


Company average (ignoring NaNs): 398846.15
Sales data with missing values replaced by company average:
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


### Question 94: Replace with Category Average

In [99]:
category_avg = np.nanmean(sales_with_missing, axis=0)

# Broadcast category averages into a full array matching shape, then use where
category_avg_broadcast = np.tile(category_avg, (sales_with_missing.shape[0], 1))
sales_filled_cat_avg = np.where(np.isnan(sales_with_missing), category_avg_broadcast, sales_with_missing)

print("Category averages (ignoring NaNs):", np.round(category_avg, 2))
print("Sales data with missing values replaced by category average:")
print(sales_filled_cat_avg)


Category averages (ignoring NaNs):

 [858000. 418750. 322500. 276250. 208750. 235000.]
Sales data with missing values replaced by category average:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


### Question 95: Missing Value Impact

In [100]:
total_before = np.nansum(sales_with_missing)
total_after_zero = sales_filled_zero.sum()

print("Total sales ignoring missing values (nansum):", total_before)
print("Total sales after replacing missing values with zero:", total_after_zero)
print("Difference:", total_before - total_after_zero)


Total sales ignoring missing values (nansum): 10370000.0
Total sales after replacing missing values with zero: 10370000.0
Difference: 0.0


## Part 17: Conditional Business Decisions

### Question 96: Store Performance Labels

In [101]:
store_labels = np.select(
    [store_wise_sales > 2800000, (store_wise_sales >= 2400000) & (store_wise_sales <= 2800000)],
    ["Excellent", "Good"],
    default="Needs Improvement"
)

for st, sales_val, label in zip(stores, store_wise_sales, store_labels):
    print(f"{st}: Sales={sales_val}, Label={label}")


Bengaluru: Sales=2270000, Label=Needs Improvement
Hyderabad: Sales=2295000, Label=Needs Improvement
Chennai: Sales=2310000, Label=Needs Improvement
Mumbai: Sales=2820000, Label=Excellent
Pune: Sales=1980000, Label=Needs Improvement


### Question 97: Profitability Classification

In [102]:
profit_labels = np.select(
    [profit_data > 200000, (profit_data >= 100000) & (profit_data <= 200000),
     (profit_data >= 0) & (profit_data < 100000), profit_data < 0],
    ["Highly Profitable", "Profitable", "Low Profit", "Loss"],
    default="Low Profit"
)

print("Profitability Classification Matrix:")
print(profit_labels)


Profitability Classification Matrix:
[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


### Question 98: Expansion Recommendation

In [103]:
expansion_mask = (store_wise_sales > 2500000) & (store_wise_profit > 700000) & (store_profit_margin > 25)

print("Stores eligible for expansion:")
eligible = stores[expansion_mask]
print(eligible if len(eligible) > 0 else "None currently eligible")


Stores eligible for expansion:
['Mumbai']


### Question 99: Category Promotion Recommendation

In [104]:
promotion_mask = (avg_sales_per_category < 300000) & (category_profit_margin > 25)

print("Categories recommended for additional promotion:")
promo_categories = categories[promotion_mask]
print(promo_categories if len(promo_categories) > 0 else "None currently qualify")


Categories recommended for additional promotion:
['Furniture' 'Beauty' 'Sports']


### Question 100: Cost Optimization Recommendation

In [105]:
cost_opt_mask = (cost_data > 250000) & (profit_margin < 25)
rows, cols = np.where(cost_opt_mask)

print("Store-category combinations needing cost optimization:")
for r, c in zip(rows, cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Cost: {cost_data[r,c]}, Margin: {profit_margin[r,c]}%")


Store-category combinations needing cost optimization:
Store: Bengaluru, Category: Electronics, Cost: 640000, Margin: 24.71%
Store: Hyderabad, Category: Electronics, Cost: 590000, Margin: 24.36%
Store: Hyderabad, Category: Groceries, Cost: 350000, Margin: 23.91%
Store: Chennai, Category: Electronics, Cost: 700000, Margin: 23.91%
Store: Chennai, Category: Groceries, Cost: 295000, Margin: 24.36%
Store: Mumbai, Category: Electronics, Cost: 790000, Margin: 24.76%
Store: Mumbai, Category: Groceries, Cost: 390000, Margin: 23.53%
Store: Pune, Category: Electronics, Cost: 530000, Margin: 23.19%
Store: Pune, Category: Groceries, Cost: 310000, Margin: 23.46%


## Part 18: Inventory Scenario

In [106]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

print("Opening Stock:\n", opening_stock)
print("Units Sold:\n", units_sold)


Opening Stock:
 [[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
Units Sold:
 [[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


### Question 101: Closing Stock

In [107]:
closing_stock = opening_stock - units_sold
print("Closing Stock:")
print(closing_stock)


Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


### Question 102: Low-Stock Identification (< 30 units)

In [108]:
low_stock_mask = closing_stock < 30
rows, cols = np.where(low_stock_mask)

print("Low-stock combinations (< 30 units):")
for r, c in zip(rows, cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Closing Stock: {closing_stock[r,c]}")


Low-stock combinations (< 30 units):
Store: Bengaluru, Category: Electronics, Closing Stock: 25
Store: Bengaluru, Category: Furniture, Closing Stock: 25
Store: Hyderabad, Category: Electronics, Closing Stock: 25
Store: Hyderabad, Category: Furniture, Closing Stock: 25
Store: Chennai, Category: Electronics, Closing Stock: 25
Store: Chennai, Category: Furniture, Closing Stock: 25
Store: Mumbai, Category: Electronics, Closing Stock: 25
Store: Pune, Category: Electronics, Closing Stock: 25
Store: Pune, Category: Furniture, Closing Stock: 20


### Question 103: Stock Availability Percentage

In [109]:
stock_availability_pct = np.round((closing_stock / opening_stock) * 100, 2)
print("Stock Availability Percentage (%):")
print(stock_availability_pct)


Stock Availability Percentage (%):
[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


### Question 104: Fast-Moving Products (> 80% sold)

In [110]:
sold_pct = (units_sold / opening_stock) * 100
fast_moving_mask = sold_pct > 80
rows, cols = np.where(fast_moving_mask)

print("Fast-moving store-category combinations (>80% sold):")
for r, c in zip(rows, cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Sold: {round(sold_pct[r,c],2)}%")


Fast-moving store-category combinations (>80% sold):
Store: Bengaluru, Category: Groceries, Sold: 84.44%
Store: Hyderabad, Category: Groceries, Sold: 84.0%
Store: Hyderabad, Category: Clothing, Sold: 82.14%
Store: Chennai, Category: Electronics, Sold: 80.77%
Store: Chennai, Category: Groceries, Sold: 83.33%
Store: Chennai, Category: Clothing, Sold: 84.38%
Store: Mumbai, Category: Electronics, Sold: 83.33%
Store: Mumbai, Category: Groceries, Sold: 85.45%
Store: Mumbai, Category: Clothing, Sold: 84.29%
Store: Pune, Category: Groceries, Sold: 82.5%


### Question 105: Category-Wise Units Sold

In [111]:
category_units_sold = units_sold.sum(axis=0)

for cat, val in zip(categories, category_units_sold):
    print(f"{cat}: {val}")


Electronics: 485
Groceries: 1950
Clothing: 1240
Furniture: 345
Beauty: 980
Sports: 720


### Question 106: Store-Wise Units Sold

In [112]:
store_units_sold = units_sold.sum(axis=1)

for st, val in zip(stores, store_units_sold):
    print(f"{st}: {val}")


Bengaluru: 1110
Hyderabad: 1175
Chennai: 1095
Mumbai: 1390
Pune: 950


### Question 107: Best Store by Unit Sales

In [113]:
best_unit_store_idx = np.argmax(store_units_sold)

print("Store with highest total unit sales:", stores[best_unit_store_idx])
print("Units sold:", store_units_sold[best_unit_store_idx])


Store with highest total unit sales: Mumbai
Units sold: 1390


### Question 108: Reorder Requirement (< 25 units)

In [114]:
reorder_mask = closing_stock < 25
print("Reorder Requirement Matrix (True = needs reorder):")
print(reorder_mask)


Reorder Requirement Matrix (True = needs reorder):
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


### Question 109: Reorder Quantity

In [115]:
# Maintain 100 units after reorder; only where closing stock < 25, else 0
reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)

print("Reorder Quantity Matrix:")
print(reorder_quantity)


Reorder Quantity Matrix:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


## Part 19: Advanced NumPy Questions

### Question 110: Cumulative Store Sales

In [116]:
cumulative_store_sales = np.cumsum(sales_data, axis=1)
print("Cumulative category sales per store:")
print(cumulative_store_sales)


Cumulative category sales per store:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


### Question 111: Cumulative Company Sales

In [117]:
cumulative_company_sales = np.cumsum(sales_data.flatten())
print("Cumulative company sales (flattened):")
print(cumulative_company_sales)


Cumulative company sales (flattened):
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


### Question 112: Sales Difference Between Categories

In [118]:
category_diff = np.diff(sales_data, axis=1)
print("Difference between consecutive category sales (per store):")
print(category_diff)


Difference between consecutive category sales (per store):
[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


### Question 113: Unique Sales Values

In [119]:
unique_values, counts = np.unique(sales_data, return_counts=True)

print("Unique sales values and their frequency:")
for val, cnt in zip(unique_values, counts):
    print(f"{val}: {cnt}")


Unique sales values and their frequency:
175000: 1
185000: 1
190000: 1
205000: 1
210000: 1
215000: 1
225000: 2
240000: 1
250000: 1
260000: 1
275000: 1
280000: 1
290000: 1
295000: 1
310000: 2
340000: 1
345000: 1
375000: 1
390000: 1
405000: 1
420000: 1
460000: 1
510000: 1
690000: 1
780000: 1
850000: 1
920000: 1
1050000: 1


### Question 114: Search for Specific Sales Value

In [120]:
target_value = 420000
exists = np.any(sales_data == target_value)
locations = np.where(sales_data == target_value)

print(f"Does {target_value} exist in sales_data?", exists)
print("Locations (store_idx, category_idx):", list(zip(locations[0], locations[1])))
for r, c in zip(locations[0], locations[1]):
    print(f"Store: {stores[r]}, Category: {categories[c]}")


Does 420000 exist in sales_data? True
Locations (store_idx, category_idx): [(np.int64(0), np.int64(1))]
Store: Bengaluru, Category: Groceries


### Question 115: Compare Sales and Cost

In [121]:
sales_gt_cost = sales_data > cost_data
print("Sales > Cost matrix:")
print(sales_gt_cost)

all_profitable = np.all(sales_gt_cost)
print("\nAre ALL store-category combinations profitable?", all_profitable)


Sales > Cost matrix:


[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]

Are ALL store-category combinations profitable? True


### Question 116: Clip Profit Values

In [122]:
clipped_profit = np.clip(profit_data, 75000, 250000)
print("Clipped Profit Matrix (min=75000, max=250000):")
print(clipped_profit)


Clipped Profit Matrix (min=75000, max=250000):


[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


### Question 117: Normalize Sales Data (Min-Max)

In [123]:
min_sales = sales_data.min()
max_sales = sales_data.max()

normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("Min-Max Normalized Sales Data:")
print(np.round(normalized_sales, 4))


Min-Max Normalized Sales Data:
[[0.7714 0.28   0.1543 0.1143 0.0171 0.0571]
 [0.6914 0.3257 0.1371 0.1543 0.04   0.0743]
 [0.8514 0.2457 0.1886 0.0971 0.0114 0.0457]
 [1.     0.3829 0.2286 0.1943 0.0857 0.1314]
 [0.5886 0.2629 0.12   0.0571 0.     0.0343]]


### Question 118: Standardize Sales Data

In [124]:
mean_sales = sales_data.mean()
std_sales = sales_data.std()

standardized_sales = (sales_data - mean_sales) / std_sales
print("Standardized Sales Data (Z-scores):")
print(np.round(standardized_sales, 4))


Standardized Sales Data (Z-scores):
[[ 2.0008  0.1339 -0.3437 -0.4957 -0.8647 -0.7128]
 [ 1.6969  0.3075 -0.4088 -0.3437 -0.7779 -0.6476]
 [ 2.3047  0.0036 -0.2135 -0.5608 -0.8864 -0.7562]
 [ 2.8692  0.5246 -0.0615 -0.1918 -0.6042 -0.4306]
 [ 1.3061  0.0687 -0.474  -0.7128 -0.9299 -0.7996]]


### Question 119: Round Values

In [125]:
two_decimal = np.round(profit_margin, 2)
nearest_whole = np.round(profit_margin, 0)
floor_values = np.floor(profit_margin)
ceil_values = np.ceil(profit_margin)

print("Two decimal places:\n", two_decimal)
print("Nearest whole number:\n", nearest_whole)
print("Floor values:\n", floor_values)
print("Ceiling values:\n", ceil_values)


Two decimal places:


 [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Nearest whole number:
 [[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
Floor values:
 [[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
Ceiling values:
 [[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


### Question 120: Save and Load Data

In [126]:
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

print("Sales data matches after load:", np.array_equal(sales_data, loaded_sales))
print("Cost data matches after load:", np.array_equal(cost_data, loaded_cost))
print("Profit data matches after load:", np.array_equal(profit_data, loaded_profit))


Sales data matches after load: True
Cost data matches after load: True
Profit data matches after load: True


## Part 20: Final Retail Analytics Project

In [127]:
# ---- Company Summary ----
final_total_sales = sales_data.sum()
final_total_cost = cost_data.sum()
final_total_profit = profit_data.sum()
final_overall_margin = round((final_total_profit / final_total_sales) * 100, 2)
avg_transaction_value = round(sales_data.mean(), 2)
highest_individual_sale = sales_data.max()
lowest_individual_sale = sales_data.min()

print("COMPANY SUMMARY")
print("Total Sales:", final_total_sales)
print("Total Cost:", final_total_cost)
print("Total Profit:", final_total_profit)
print("Overall Profit Margin:", final_overall_margin, "%")
print("Average Transaction Value:", avg_transaction_value)
print("Highest Individual Sales Value:", highest_individual_sale)
print("Lowest Individual Sales Value:", lowest_individual_sale)


COMPANY SUMMARY
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34 %
Average Transaction Value: 389166.67
Highest Individual Sales Value: 1050000
Lowest Individual Sales Value: 175000


In [ ]:
# ---- Store Summary ----
# ensure numpy is available in the current kernel and import it
import sys, subprocess
try:
    import numpy as np
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
    import numpy as np
print("STORE SUMMARY")
stores = np.array(["Store A", "Store B", "Store C", "Store D", "Store E"])

for i, st in enumerate(stores):
    print(f"\n{st}:")
    print(f"  Total Sales: {store_wise_sales[i]}")
    print(f"  Total Cost: {store_wise_cost[i]}")
    print(f"  Total Profit: {store_wise_profit[i]}")
    print(f"  Profit Margin: {store_profit_margin[i]}%")
    print(f"  Targets Achieved: {targets_met_per_store[i]} / {len(categories)}")
    print(f"  Total Units Sold: {store_units_sold[i]}")
    is_eligible = (store_wise_sales[i] > 2500000) and (store_wise_profit[i] > 700000) and (store_profit_margin[i] > 25)
    print(f"  Expansion Eligible: {is_eligible}")


In [ ]:
# ---- Category Summary ----
print("CATEGORY SUMMARY")
for i, cat in enumerate(categories):
    print(f"\n{cat}:")
    print(f"  Total Sales: {category_wise_sales[i]}")
    print(f"  Total Cost: {category_wise_cost[i]}")
    print(f"  Total Profit: {category_wise_profit[i]}")
    print(f"  Profit Margin: {category_profit_margin[i]}%")
    print(f"  Average Sales: {round(avg_sales_per_category[i], 2)}")
    print(f"  Stores Achieving Target: {targets_met_per_category[i]} / {len(stores)}")
    print(f"  Total Units Sold: {category_units_sold[i]}")


CATEGORY SUMMARY

Electronics:
  Total Sales: 4290000
  Total Cost: 3250000
  Total Profit: 1040000
  Profit Margin: 24.24%
  Average Sales: 858000.0
  Stores Achieving Target: 3 / 5
  Total Units Sold: 485

Groceries:
  Total Sales: 2185000
  Total Cost: 1660000
  Total Profit: 525000
  Profit Margin: 24.03%
  Average Sales: 437000.0
  Stores Achieving Target: 2 / 5
  Total Units Sold: 1950

Clothing:
  Total Sales: 1600000
  Total Cost: 1145000
  Total Profit: 455000
  Profit Margin: 28.44%
  Average Sales: 320000.0
  Stores Achieving Target: 2 / 5
  Total Units Sold: 1240

Furniture:
  Total Sales: 1415000
  Total Cost: 1045000
  Total Profit: 370000
  Profit Margin: 26.15%
  Average Sales: 283000.0
  Stores Achieving Target: 2 / 5
  Total Units Sold: 345

Beauty:
  Total Sales: 1010000
  Total Cost: 665000
  Total Profit: 345000
  Profit Margin: 34.16%
  Average Sales: 202000.0
  Stores Achieving Target: 2 / 5
  Total Units Sold: 980

Sports:
  Total Sales: 1175000
  Total Cost: 83

In [ ]:
# ---- Management Recommendations ----
best_store_idx = np.argmax(store_wise_sales)
worst_store_idx = np.argmin(store_wise_sales)
most_profitable_cat_idx_f = np.argmax(category_wise_profit)
least_profitable_cat_idx_f = np.argmin(category_wise_profit)

expansion_eligible_stores = stores[expansion_mask]
promotion_categories_final = categories[promotion_mask]

cost_opt_rows, cost_opt_cols = np.where(cost_opt_mask)
reorder_rows, reorder_cols = np.where(reorder_mask)

print("MANAGEMENT RECOMMENDATIONS")
print("1. Best-performing store (by sales):", stores[best_store_idx])
print("2. Lowest-performing store (by sales):", stores[worst_store_idx])
print("3. Most profitable category:", categories[most_profitable_cat_idx_f])
print("4. Lowest-profit category:", categories[least_profitable_cat_idx_f])
print("5. Store(s) recommended for expansion:", list(expansion_eligible_stores) if len(expansion_eligible_stores) else "None")
print("6. Category(ies) requiring additional marketing:", list(promotion_categories_final) if len(promotion_categories_final) else "None")
print("7. Store-category combos needing cost optimization:")
for r, c in zip(cost_opt_rows, cost_opt_cols):
    print(f"   - {stores[r]} / {categories[c]}")
print("8. Store-category combos requiring inventory reorder:")
for r, c in zip(reorder_rows, reorder_cols):
    print(f"   - {stores[r]} / {categories[c]} (Closing Stock: {closing_stock[r,c]}, Reorder Qty: {reorder_quantity[r,c]})")


MANAGEMENT RECOMMENDATIONS
1. Best-performing store (by sales): Mumbai
2. Lowest-performing store (by sales): Pune
3. Most profitable category: Electronics
4. Lowest-profit category: Sports
5. Store(s) recommended for expansion: [np.str_('Mumbai')]
6. Category(ies) requiring additional marketing: [np.str_('Furniture'), np.str_('Beauty'), np.str_('Sports')]
7. Store-category combos needing cost optimization:
   - Bengaluru / Electronics
   - Hyderabad / Electronics
   - Hyderabad / Groceries
   - Chennai / Electronics
   - Chennai / Groceries
   - Mumbai / Electronics
   - Mumbai / Groceries
   - Pune / Electronics
   - Pune / Groceries
8. Store-category combos requiring inventory reorder:
   - Pune / Furniture (Closing Stock: 20, Reorder Qty: 80)


In [ ]:
# ---- Final Formatted Report ----
print("=" * 60)
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("=" * 60)

print("\nCOMPANY SUMMARY")
print("-" * 15)
print(f"Total Sales: {final_total_sales}")
print(f"Total Cost: {final_total_cost}")
print(f"Total Profit: {final_total_profit}")
print(f"Overall Profit Margin: {final_overall_margin}%")

print("\nBEST-PERFORMING STORE")
print("-" * 21)
print(f"Store: {stores[best_store_idx]}")
print(f"Sales: {store_wise_sales[best_store_idx]}")
print(f"Cost: {store_wise_cost[best_store_idx]}")
print(f"Profit: {store_wise_profit[best_store_idx]}")
print(f"Profit Margin: {store_profit_margin[best_store_idx]}%")

print("\nMOST PROFITABLE CATEGORY")
print("-" * 24)
print(f"Category: {categories[most_profitable_cat_idx_f]}")
print(f"Sales: {category_wise_sales[most_profitable_cat_idx_f]}")
print(f"Cost: {category_wise_cost[most_profitable_cat_idx_f]}")
print(f"Profit: {category_wise_profit[most_profitable_cat_idx_f]}")
print(f"Profit Margin: {category_profit_margin[most_profitable_cat_idx_f]}%")

print("\nEXPANSION RECOMMENDATIONS")
print("-" * 25)
print("Eligible Stores:", list(expansion_eligible_stores) if len(expansion_eligible_stores) else "None currently eligible")

print("\nCOST OPTIMIZATION")
print("-" * 17)
for r, c in zip(cost_opt_rows, cost_opt_cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Cost: {cost_data[r,c]}, Profit Margin: {profit_margin[r,c]}%")

print("\nINVENTORY REORDER")
print("-" * 17)
for r, c in zip(reorder_rows, reorder_cols):
    print(f"Store: {stores[r]}, Category: {categories[c]}, Closing Stock: {closing_stock[r,c]}, Reorder Quantity: {reorder_quantity[r,c]}")



SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34%

BEST-PERFORMING STORE
---------------------
Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000
Profit Margin: 26.77%

MOST PROFITABLE CATEGORY
------------------------
Category: Electronics
Sales: 4290000
Cost: 3250000
Profit: 1040000
Profit Margin: 24.24%

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores: [np.str_('Mumbai')]

COST OPTIMIZATION
-----------------
Store: Bengaluru, Category: Electronics, Cost: 640000, Profit Margin: 24.71%
Store: Hyderabad, Category: Electronics, Cost: 590000, Profit Margin: 24.36%
Store: Hyderabad, Category: Groceries, Cost: 350000, Profit Margin: 23.91%
Store: Chennai, Category: Electronics, Cost: 700000, Profit Margin: 23.91%
Store: Chennai, Category: Groceries, Cost: 295000, Profit Margin: 24.36%
Store: Mumbai, Category: Electronics, Cost: 790000, Profit Margin: 